# Used for macOS
name: raopt
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - h5py=2.10.0
  - hdf5=1.10.6
  - matplotlib=3.5.1
  - numpy-base=1.21.5
  - pandas=1.4.2
  - pip=21.2.4
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - shapely=1.7.1
  - tensorboard=2.4.0
  - tensorflow=2.4.1
#  - tensorflow-gpu=2.4.1
  - tqdm=4.64.0
  - pip:
    - haversine==2.5.1
    - numpy==1.19.2
    - utm==0.7.0
